name: TyrantPickaxe
version: '1.0'
main: com.example.tyrantpickaxe.TyrantPickaxe
api-version: '1.21'
author: Gemini
description: A powerful pickaxe for tyrants.
commands:
  givetp:
    description: 获得暴君之镐 (Gives the Tyrant Pickaxe)
    usage: /<command>
    permission: tyrantpickaxe.get
permissions:
  tyrantpickaxe.get:
    description: 允许玩家使用 /givetp 指令
    default: op
