name: GodsExecutioner
version: 1.0.0
main: com.example.godsexecutioner.GodsExecutionerPlugin
api-version: '1.21'
description: 神之执行者武器插件
author: YourName

commands:
  getexecutioner:
    description: 获取神之执行者
    usage: /getexecutioner [player]
    permission: godsexecutioner.give
    aliases: [ge, executioner]

permissions:
  godsexecutioner.give:
    description: 允许获取神之执行者
    default: op
  godsexecutioner.use:
    description: 允许使用神之执行者
    default: true
  godsexecutioner.craft:
    description: 允许合成神之执行者
    default: true
