# [file name]: plugin.yml
name: DeathCrown
version: 1.0.0
main: com.yourname.deathcrown.DeathCrownPlugin
api-version: 1.21
description: 死亡王冠 - 溺尸王召唤器附属插件
author: YourName
website: https://yourwebsite.com

depend: [DrownedKing]

commands:
  deathcrown:
    description: 死亡王冠管理命令
    usage: /<command> <give|reset|status|reload|help>
    permission: deathcrown.use

permissions:
  deathcrown.use:
    description: 使用死亡王冠基础权限
    default: op
  deathcrown.give:
    description: 给予死亡王冠权限
    default: op
  deathcrown.admin:
    description: 死亡王冠管理权限
    default: op
