name: NetherControl
version: 1.1.0
main: com.yourname.nethercontrol.NetherControlPlugin
api-version: 1.19
depend: [CreditPlugin]  # 添加对CreditPlugin的依赖
description: 地狱门控制系统，集成信用点功能
author: YourName

commands:
  nethercontrol:
    description: 地狱门控制命令
    usage: /<command> <reload|status|give|set|checkcredit>
    permission: nethercontrol.use
    aliases: [nctl]

permissions:
  nethercontrol.use:
    description: 使用地狱门控制基础命令
    default: true
  nethercontrol.admin:
    description: 地狱门控制管理权限
    default: op
