name: DrownedKing
version: 1.0.0
main: com.yourname.drownedking.DrownedKingPlugin
api-version: "1.21"
description: 独立的溺尸王Boss插件
author: YourName
website: https://example.com

commands:
  drownedking:
    description: 溺尸王Boss系统命令
    usage: /<command> <spawn|list|reload|help>
    permission: drownedking.use
    aliases: [dk, boss]

permissions:
  drownedking.use:
    description: 使用溺尸王基础命令
    default: op
  drownedking.spawn:
    description: 生成溺尸王
    default: op
  drownedking.list:
    description: 查看活跃Boss列表
    default: op
  drownedking.reload:
    description: 重载插件配置
    default: op
  drownedking.admin:
    description: 所有管理员权限
    default: op
  drownedking.addtreasure:
    description: 允许添加溺尸王宝藏袋物品
    default: op
  drownedking.listtreasure:
    description: 允许查看溺尸王宝藏袋物品列表
    default: op
  drownedking.removetreasure:
    description: 允许移除溺尸王宝藏袋物品
    default: op   
