name: PlayerHirePlugin
version: 1.0.0
main: com.yourname.playerhireplugin.PlayerHirePlugin
api-version: "1.21"
depend: [CreditPlugin]
description: 玩家雇佣市场插件 - 允许玩家雇佣其他玩家作为刺客
author: YourName
website: https://yoursite.com

commands:
  hire:
    description: 打开玩家雇佣市场
    usage: /<command> [gui|offer|accept|contracts|reload]
    permission: hire.use
    permission-message: 你没有权限使用此命令

permissions:
  hire.use:
    description: 允许使用雇佣市场基本功能
    default: true
  hire.admin:
    description: 允许使用雇佣市场管理功能
    default: op
