name: CreditDebitNote
version: 1.0.0
main: com.yourname.creditdebitnote.CreditDebitNote
api-version: 1.16
depend: [CreditPlugin]
description: 信用点借记单系统附属插件
author: yourname
commands:
  debit:
    description: 信用点借记单管理命令
    usage: /<command> set <金额>
