name: TyrantBossPlugin
version: 1.0.0
main: com.yourname.tyrantboss.TyrantBossPlugin
api-version: 1.19
commands:
  spawntyrant:
    description: 生成暴君Boss
    usage: /spawntyrant
    permission: tyrantboss.spawn
  tyrantreload:
    description: 重新加载暴君插件配置
    usage: /tyrantreload
    permission: tyrantboss.reload
  tyrantaddtreasure:
    description: 添加物品到宝藏袋
    usage: /tyrantaddtreasure <奖励ID> <概率>
    permission: tyrantboss.addtreasure
  tyrantlisttreasure:
    description: 列出宝藏袋中的所有物品
    usage: /tyrantlisttreasure
    permission: tyrantboss.listtreasure
  tyrantremovetreasure:
    description: 从宝藏袋中移除物品
    usage: /tyrantremovetreasure <奖励ID>
    permission: tyrantboss.removetreasure
permissions:
  tyrantboss.*:
    description: 暴君Boss插件的所有权限
    children:
      tyrantboss.spawn: true
      tyrantboss.reload: true
      tyrantboss.addtreasure: true
      tyrantboss.listtreasure: true
      tyrantboss.removetreasure: true
  tyrantboss.spawn:
    description: 生成暴君Boss的权限
    default: op
  tyrantboss.reload:
    description: 重新加载配置的权限
    default: op
  tyrantboss.addtreasure:
    description: 添加宝藏袋物品的权限
    default: op
  tyrantboss.listtreasure:
    description: 查看宝藏袋物品的权限
    default: op
  tyrantboss.removetreasure:
    description: 移除宝藏袋物品的权限
    default: op
